apiVersion: v1
kind: Service
metadata:
  name: mynewsvc
  labels:
    app: mynewsvc
spec:
  type: NodePort
  selector:
    app: mydep        # Match this to your pod's label
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32000

